[features]
seeds = false
skip-lint = false
[programs.devnet]
swap = "kWmvwPUFQ1UPZ9KqjmJv7GW5w7ghkwVpN9NMLJjpDY5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/Desktop/Workspace/SeCbhUgwfifKUVc3Ut5Z7hRCRMsPyFr1Z4hyargXYYv.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
