[features]
seeds = false
skip-lint = false
[programs.devnet]
swap = "HG4rN1XSQQrEMjfZCiS88WkBEQaLbNyTtPopuHsgc1gq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/usamaali/Desktop/Workspace/testProjects/TeKnfk7V3czXB17nexc5bzqa4hQyv6hTQwgdnJhSQuy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
